### PR TITLE
Strict check for argument `pattern` in io.actionChannel

### LINKED ISSUE #1532: Error: invalid pattern: undefined
#### Description of the bug/issue
After upgraded from 0.16 to beta.1 I'm now getting an error message and my sagas bomb out and don't run.  Any ideas? 
#### Steps to reproduce the bug/issue

1. First saga runs via throttle and outputs action
Saga:
```
function * doStats(){
  if (moment().subtract(statIntervalSec,'seconds').valueOf() > lastTime.valueOf())
  {
    lastTime = moment();
    global.log.info('doing stats');
    yield deviceInfo();
    yield epilogInfo();
  }}

export function * doStatsSagaWithDelay(){
  yield throttle(statIntervalSec*1000,'*',doStats);
}
```
Action output
```
{type:"STAT_PHONE"
value:Object
batteryLevel:100
deviceId:"msm8998"
freeDiskStorage:"1677MB"
maxMemory:"263MB"
totalDiskStorage:"-1194MB"
totalMemory:"7904MB"
type:"STAT_PHONE"
usedMemory:"tbd"
Symbol(@@redux-saga/SAGA_ACTION):true

```
2. I see this message in console and saga's no longer run
```
ExceptionsManager.js:71 Error: invalid pattern: undefined
    at matcher (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:90118:13)
    at blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:90077:16
    at Array.some (native)
    at Function.<anonymous> (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:90076:23)
    at put (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:89847:34)
    at Object.chan.put (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:89878:9)
    at blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:89156:19
    at dispatch (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:71539:20)
    at blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:89509:14
    at blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:90705:54 ""

15:34:00.950 ExceptionsManager.js:71 The above error occurred in task deviceInfo
    created by rootSaga
Tasks cancelled due to error:
scanRequestHandler
deviceFoundHandler
scanStoppedHandler
disconnectedDeviceHandler
getRSSIforConnectedDevices
connectionSuccessHandler
firmwareLoadedHandler
loadSupportedFwVersion
deviceInfoLoadedHandler
stateRquesthandler
batteryAndImpRequestHandler
deleteRecordingsHandler
requestMissingPageAfterRT
handleMissingPagesAndEventsOnDock
readCharHandler
requestRecordingsHandler
doStatsSaga
doStatsSagaWithDelay
epilogConnectedSaga
crActionsOfInterest
storeCompletedEegPages 

```

package.json
```
...
  "react": "16.3.1",
    "react-addons-update": "^15.6.2",
    "react-mixin": "^4.0.0",
    "react-native": "0.55.4",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-saga": "^1.0.0-beta.1",
...
```

### PR DESCRIPTION
**Pull request by shinima**
| Q                        | A  |
| ------------------------ | ---  |
| Fixed Issues?            | Fixes #1532 |
| Patch: Bug Fix?          |    |
| Major: Breaking Change?  |    |
| Minor: New Feature?      |    |
| Tests Added + Pass?      |  |
| Any Dependency Changes?  |    |

Use `is.pattern` to check argument `pattern` instead of `is.notUndef`. Error with an *invalid pattern* message will be thrown when constructing the action-channel, so it is much easier to debug errors in #1532.

### CODE REVIEW

**Comment by Andarist** [comment]
I'm not sure though if this fix the other issue completely. I'd like to debug the reported issue to see if we can improve it any further.
