### ISSUE TITLE
Error: invalid pattern: undefined

### ISSUE THREAD

**Issue by anwarhamr** [redux-saga/redux-saga#1532]
#### Description of the bug/issue
After upgraded from 0.16 to beta.1 I'm now getting an error message and my sagas bomb out and don't run.  Any ideas? 
#### Steps to reproduce the bug/issue

1. First saga runs via throttle and outputs action
Saga:
```
function * doStats(){
  if (moment().subtract(statIntervalSec,'seconds').valueOf() > lastTime.valueOf())
  {
    lastTime = moment();
    global.log.info('doing stats');
    yield deviceInfo();
    yield epilogInfo();
  }}

export function * doStatsSagaWithDelay(){
  yield throttle(statIntervalSec*1000,'*',doStats);
}
```
Action output
```
{type:"STAT_PHONE"
value:Object
batteryLevel:100
deviceId:"msm8998"
freeDiskStorage:"1677MB"
maxMemory:"263MB"
totalDiskStorage:"-1194MB"
totalMemory:"7904MB"
type:"STAT_PHONE"
usedMemory:"tbd"
Symbol(@@redux-saga/SAGA_ACTION):true

```
2. I see this message in console and saga's no longer run
```
ExceptionsManager.js:71 Error: invalid pattern: undefined
    at matcher (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:90118:13)
    at blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:90077:16
    at Array.some (native)
    at Function.<anonymous> (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:90076:23)
    at put (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:89847:34)
    at Object.chan.put (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:89878:9)
    at blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:89156:19
    at dispatch (blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:71539:20)
    at blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:89509:14
    at blob:file:///e9088396-ba97-4270-b1c3-e826e1c1584d:90705:54 ""

15:34:00.950 ExceptionsManager.js:71 The above error occurred in task deviceInfo
    created by rootSaga
Tasks cancelled due to error:
scanRequestHandler
deviceFoundHandler
scanStoppedHandler
disconnectedDeviceHandler
getRSSIforConnectedDevices
connectionSuccessHandler
firmwareLoadedHandler
loadSupportedFwVersion
deviceInfoLoadedHandler
stateRquesthandler
batteryAndImpRequestHandler
deleteRecordingsHandler
requestMissingPageAfterRT
handleMissingPagesAndEventsOnDock
readCharHandler
requestRecordingsHandler
doStatsSaga
doStatsSagaWithDelay
epilogConnectedSaga
crActionsOfInterest
storeCompletedEegPages 

```

package.json
```
...
  "react": "16.3.1",
    "react-addons-update": "^15.6.2",
    "react-mixin": "^4.0.0",
    "react-native": "0.55.4",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-saga": "^1.0.0-beta.1",
...
```

**Comment by restrry** [comment]
what is `deviceInfo` ? why you call it as `yield deviceInfo()`? according to error message that's the error occurred during this call

**Comment by shinima** [comment]
@restrry   I think `deviceInfo` is a generator function, and `yield deviceInfo()` is fine since we allow yielding iterators.  In most situations, `yield deviceInfo()` has the same effect as `yield call(deviceInfo)` except for test-ability.

@anwarhamr  the error is thrown inside `deviceInfo()`, you need to check that function carefully.

**Comment by anwarhamr** [comment]
I don't see anything that could cause a problem.  In addition the action mentioned in my initial post `type:STAT_PHONE` is the result of `deviceInfo` call.

Below is the deviceInfo generator, do you see anything that could be going wrong?  Seems pretty straight forward.  I'll mention again that this all works fine in `0.16.0`
```
export function * deviceInfo(){
  let value = yield   DeviceInfo.getBatteryLevel();

  console.log('DeviceInfo.getTotalDiskCapacity()',DeviceInfo.getTotalDiskCapacity());
  let data = {
    type:c.STAT_PHONE,
    batteryLevel:parseInt(value *100),
    deviceId:DeviceInfo.getDeviceId(),
    totalDiskStorage: convertBytes(DeviceInfo.getTotalDiskCapacity()),
    freeDiskStorage: convertBytes(DeviceInfo.getFreeDiskStorage()),
    maxMemory:convertBytes( DeviceInfo.getMaxMemory()),
    usedMemory:'tbd',//convertBytes( DeviceInfo.getUsedMemory()),
    totalMemory: convertBytes(DeviceInfo.getTotalMemory()),
    //todo
    //storagePageCount
    //pagesPushedToCloudCount
  };
  yield put ({type:c.STAT_PHONE,value:data});

}
```

**Comment by shinima** [comment]
Hey @anwarhamr , I can not tell why the error appears. The error `invalid pattern: undefined` is thrown from [src/internal/matcher.js#L21-L23](https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/matcher.js#L21-L23), you could add a breakpoint here and it should become much easier to debug. 

You may need to add the breakpoint in the corresponding redux-saga distributions files. Find `internal\matcher.js` in `node_modules/redux-saga/es` or in `node_modules/redux-saga/lib`.

![image](https://user-images.githubusercontent.com/5550931/43005575-d9e4d490-8c65-11e8-8e1d-449f2116537b.png)

**Comment by anwarhamr** [comment]
@shinima OK that did it for me.  The problem is mine but I think we can do better here with more information when an error occurs.  Here is my suggestion, I'll make the change if you think it worthy. 

`matcher.js` has an array function that can catch and rethrow the error with the pattern variable or something further up the chain that would point to the correct saga that is causing the error.  In my case it wasn't the `deviceInfo` saga at all but another saga in another file that had an action constant in the the actionChannel list that was undefined... See saga below.
```
function * crActionsOfInterest(){

  const chan = yield actionChannel(
    [
      'ERROR',
      c.DEVICE_INFORMATION_LOADED,
      c.DEVICE_DISCONNECTED,
      c.EPILOG_READY,
      c.EPILOG_CLOCK_SET,  <-- this value was undefined. 
      c.EPILOG_DELETE_RECORDINGS_COMPLETE,
      c.EPILOG_EVENT_DATA_RECEIVED,
      c.EPILOG_MESSAGE_DATA_RECEIVED,
      c.EPILOG_RA_EEG_DATA_RECEIVED,
      c.EPILOG_RT_EEG_DATA_RECEIVED,
      c.STAT_EPILOG,
      c.STAT_PHONE,
    ]
  );
  let a = null;
  try {
    while (true) {
...}}
```

Here is my suggested change:
```
var array = function array(patterns) {
  return function (input) {
    return patterns.some(function (p) {
     try{
      return matcher(p)(input);
     }
      catch(e){ 
       throw new Error('Pattern match error ' + e.message + ' for value in:'+patterns) // It would be great if it possible to include a saga/function/generator name...
}
    });
  };
};
...
function matcher(pattern) {
  // prettier-ignore
  var matcherCreator = pattern === '*' ? wildcard : _utils.is.string(pattern) ? string : _utils.is.array(pattern) ? array : _utils.is.stringableFunc(pattern) ? string : _utils.is.func(pattern) ? predicate : _utils.is.symbol(pattern) ? symbol : null;

  if (matcherCreator === null) {
    throw new Error("invalid pattern: " + pattern);
  }

  return matcherCreator(pattern);
}
```

**Comment by Andarist** [comment]
I wouldnt like to be so defensive in the code. I dont fully understand the problem at hand (why wrong saga was reported to be causing the problem) - could u reproduce this on something like codesandbox.io ? It's possible that there is a bug sitting somewhere else and could be fixed.

**Comment by shinima** [comment]
Here is a [reproduction](https://codesandbox.io/s/l5zvo86v19).

**Comment by restrry** [comment]
the problem is that we don't check if array contains only valid patterns. so when user calls 
`yield actionChannel([undefined])`
we just add a taker with passed array https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/proc.js#L638-L652
but when use call `put()` channel throws trying to call taker https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/matcher.js#L4

so actually error happens during the `put`.
we can fix the problem if check that array contains valid patterns like
```js
//@redux-saga/is
export function pattern (candidate) {
  if(candidate){
    if(string(candidate) || symbol(candidate) || func(candidate)) return true
    if(array(candidate) && candidate.every(pattern)) return true
  }
  return false;
}
```

**Comment by Andarist** [comment]
sure, seems like a good check 👍
